server:
  port: 9080
  
management:
    port: 9094
    address: 127.0.0.1
  
spring:
    application:
        exchange: payments.events.fanout.exchange
        queue: screening.default.queue
        databaseName: paymentsdb
        eventsCollectionName: events
        snapshotCollectionName: snapshots
    rabbitmq:
        hostname: localhost
        username: test
        password: password
      
logging:
    level:
        root: INFO
        org.springframework: INFO
        org.axonframework: INFO
        payments: INFO
    file: ./logs/screening-service.log
